// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: engine_service.proto

package engine

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SecurityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ClientIp      string                 `protobuf:"bytes,2,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	UserAgent     string                 `protobuf:"bytes,3,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	RequestMethod string                 `protobuf:"bytes,4,opt,name=request_method,json=requestMethod,proto3" json:"request_method,omitempty"`
	RequestPath   string                 `protobuf:"bytes,5,opt,name=request_path,json=requestPath,proto3" json:"request_path,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,6,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          []byte                 `protobuf:"bytes,7,opt,name=body,proto3" json:"body,omitempty"`
	SessionId     string                 `protobuf:"bytes,8,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserId        string                 `protobuf:"bytes,9,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecurityRequest) Reset() {
	*x = SecurityRequest{}
	mi := &file_engine_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecurityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityRequest) ProtoMessage() {}

func (x *SecurityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engine_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecurityRequest.ProtoReflect.Descriptor instead.
func (*SecurityRequest) Descriptor() ([]byte, []int) {
	return file_engine_service_proto_rawDescGZIP(), []int{0}
}

func (x *SecurityRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SecurityRequest) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *SecurityRequest) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *SecurityRequest) GetRequestMethod() string {
	if x != nil {
		return x.RequestMethod
	}
	return ""
}

func (x *SecurityRequest) GetRequestPath() string {
	if x != nil {
		return x.RequestPath
	}
	return ""
}

func (x *SecurityRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *SecurityRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *SecurityRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SecurityRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type SecurityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	IsMalicious   bool                   `protobuf:"varint,2,opt,name=is_malicious,json=isMalicious,proto3" json:"is_malicious,omitempty"`
	ThreatScore   float64                `protobuf:"fixed64,3,opt,name=threat_score,json=threatScore,proto3" json:"threat_score,omitempty"`
	RiskFactors   []string               `protobuf:"bytes,4,rep,name=risk_factors,json=riskFactors,proto3" json:"risk_factors,omitempty"`
	Confidence    float64                `protobuf:"fixed64,5,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecurityResponse) Reset() {
	*x = SecurityResponse{}
	mi := &file_engine_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecurityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityResponse) ProtoMessage() {}

func (x *SecurityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engine_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecurityResponse.ProtoReflect.Descriptor instead.
func (*SecurityResponse) Descriptor() ([]byte, []int) {
	return file_engine_service_proto_rawDescGZIP(), []int{1}
}

func (x *SecurityResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SecurityResponse) GetIsMalicious() bool {
	if x != nil {
		return x.IsMalicious
	}
	return false
}

func (x *SecurityResponse) GetThreatScore() float64 {
	if x != nil {
		return x.ThreatScore
	}
	return 0
}

func (x *SecurityResponse) GetRiskFactors() []string {
	if x != nil {
		return x.RiskFactors
	}
	return nil
}

func (x *SecurityResponse) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *SecurityResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_engine_service_proto protoreflect.FileDescriptor

const file_engine_service_proto_rawDesc = "" +
	"\n" +
	"\x14engine_service.proto\x12\x13phantom_flow.engine\"\x8b\x03\n" +
	"\x0fSecurityRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1b\n" +
	"\tclient_ip\x18\x02 \x01(\tR\bclientIp\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x03 \x01(\tR\tuserAgent\x12%\n" +
	"\x0erequest_method\x18\x04 \x01(\tR\rrequestMethod\x12!\n" +
	"\frequest_path\x18\x05 \x01(\tR\vrequestPath\x12K\n" +
	"\aheaders\x18\x06 \x03(\v21.phantom_flow.engine.SecurityRequest.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\a \x01(\fR\x04body\x12\x1d\n" +
	"\n" +
	"session_id\x18\b \x01(\tR\tsessionId\x12\x17\n" +
	"\auser_id\x18\t \x01(\tR\x06userId\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xcb\x01\n" +
	"\x10SecurityResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12!\n" +
	"\fis_malicious\x18\x02 \x01(\bR\visMalicious\x12!\n" +
	"\fthreat_score\x18\x03 \x01(\x01R\vthreatScore\x12!\n" +
	"\frisk_factors\x18\x04 \x03(\tR\vriskFactors\x12\x1e\n" +
	"\n" +
	"confidence\x18\x05 \x01(\x01R\n" +
	"confidence\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error2h\n" +
	"\x0eSecurityEngine\x12V\n" +
	"\aAnalyze\x12$.phantom_flow.engine.SecurityRequest\x1a%.phantom_flow.engine.SecurityResponseB8Z6github.com/phantom-flow/security-platform/proto/engineb\x06proto3"

var (
	file_engine_service_proto_rawDescOnce sync.Once
	file_engine_service_proto_rawDescData []byte
)

func file_engine_service_proto_rawDescGZIP() []byte {
	file_engine_service_proto_rawDescOnce.Do(func() {
		file_engine_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_engine_service_proto_rawDesc), len(file_engine_service_proto_rawDesc)))
	})
	return file_engine_service_proto_rawDescData
}

var file_engine_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_engine_service_proto_goTypes = []any{
	(*SecurityRequest)(nil),  // 0: phantom_flow.engine.SecurityRequest
	(*SecurityResponse)(nil), // 1: phantom_flow.engine.SecurityResponse
	nil,                      // 2: phantom_flow.engine.SecurityRequest.HeadersEntry
}
var file_engine_service_proto_depIdxs = []int32{
	2, // 0: phantom_flow.engine.SecurityRequest.headers:type_name -> phantom_flow.engine.SecurityRequest.HeadersEntry
	0, // 1: phantom_flow.engine.SecurityEngine.Analyze:input_type -> phantom_flow.engine.SecurityRequest
	1, // 2: phantom_flow.engine.SecurityEngine.Analyze:output_type -> phantom_flow.engine.SecurityResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_engine_service_proto_init() }
func file_engine_service_proto_init() {
	if File_engine_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_engine_service_proto_rawDesc), len(file_engine_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_engine_service_proto_goTypes,
		DependencyIndexes: file_engine_service_proto_depIdxs,
		MessageInfos:      file_engine_service_proto_msgTypes,
	}.Build()
	File_engine_service_proto = out.File
	file_engine_service_proto_goTypes = nil
	file_engine_service_proto_depIdxs = nil
}
