// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package engine

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

const SecurityEngine_Analyze_FullMethodName = "/phantom_flow.engine.SecurityEngine/Analyze"

type SecurityEngineClient interface {
	Analyze(ctx context.Context, in *SecurityRequest, opts ...grpc.CallOption) (*SecurityResponse, error)
}

type securityEngineClient struct {
	cc grpc.ClientConnInterface
}

func NewSecurityEngineClient(cc grpc.ClientConnInterface) SecurityEngineClient {
	return &securityEngineClient{cc}
}

func (c *securityEngineClient) Analyze(ctx context.Context, in *SecurityRequest, opts ...grpc.CallOption) (*SecurityResponse, error) {
	out := new(SecurityResponse)
	err := c.cc.Invoke(ctx, SecurityEngine_Analyze_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

type SecurityEngineServer interface {
	Analyze(context.Context, *SecurityRequest) (*SecurityResponse, error)
	mustEmbedUnimplementedSecurityEngineServer()
}

type UnimplementedSecurityEngineServer struct{}

func (UnimplementedSecurityEngineServer) Analyze(context.Context, *SecurityRequest) (*SecurityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Analyze not implemented")
}

func (UnimplementedSecurityEngineServer) mustEmbedUnimplementedSecurityEngineServer() {}

type UnsafeSecurityEngineServer interface {
	mustEmbedUnimplementedSecurityEngineServer()
}

func RegisterSecurityEngineServer(s grpc.ServiceRegistrar, srv SecurityEngineServer) {
	s.RegisterService(&SecurityEngine_ServiceDesc, srv)
}

func _SecurityEngine_Analyze_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SecurityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecurityEngineServer).Analyze(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecurityEngine_Analyze_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecurityEngineServer).Analyze(ctx, req.(*SecurityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var SecurityEngine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "phantom_flow.engine.SecurityEngine",
	HandlerType: (*SecurityEngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Analyze",
			Handler:    _SecurityEngine_Analyze_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "engine_service.proto",
}
