// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: ml_service.proto

package ml

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PredictRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Features      []float64              `protobuf:"fixed64,1,rep,packed,name=features,proto3" json:"features,omitempty"`
	IpAddress     string                 `protobuf:"bytes,2,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	UserAgent     string                 `protobuf:"bytes,3,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	RequestPath   string                 `protobuf:"bytes,4,opt,name=request_path,json=requestPath,proto3" json:"request_path,omitempty"`
	RequestMethod string                 `protobuf:"bytes,5,opt,name=request_method,json=requestMethod,proto3" json:"request_method,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PredictRequest) Reset() {
	*x = PredictRequest{}
	mi := &file_ml_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictRequest) ProtoMessage() {}

func (x *PredictRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ml_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictRequest.ProtoReflect.Descriptor instead.
func (*PredictRequest) Descriptor() ([]byte, []int) {
	return file_ml_service_proto_rawDescGZIP(), []int{0}
}

func (x *PredictRequest) GetFeatures() []float64 {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *PredictRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *PredictRequest) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *PredictRequest) GetRequestPath() string {
	if x != nil {
		return x.RequestPath
	}
	return ""
}

func (x *PredictRequest) GetRequestMethod() string {
	if x != nil {
		return x.RequestMethod
	}
	return ""
}

type PredictResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ThreatScore   float64                `protobuf:"fixed64,2,opt,name=threat_score,json=threatScore,proto3" json:"threat_score,omitempty"`
	AnomalyScore  float64                `protobuf:"fixed64,3,opt,name=anomaly_score,json=anomalyScore,proto3" json:"anomaly_score,omitempty"`
	Confidence    float64                `protobuf:"fixed64,4,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PredictResponse) Reset() {
	*x = PredictResponse{}
	mi := &file_ml_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictResponse) ProtoMessage() {}

func (x *PredictResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ml_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictResponse.ProtoReflect.Descriptor instead.
func (*PredictResponse) Descriptor() ([]byte, []int) {
	return file_ml_service_proto_rawDescGZIP(), []int{1}
}

func (x *PredictResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PredictResponse) GetThreatScore() float64 {
	if x != nil {
		return x.ThreatScore
	}
	return 0
}

func (x *PredictResponse) GetAnomalyScore() float64 {
	if x != nil {
		return x.AnomalyScore
	}
	return 0
}

func (x *PredictResponse) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *PredictResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_ml_service_proto protoreflect.FileDescriptor

const file_ml_service_proto_rawDesc = "" +
	"\n" +
	"\x10ml_service.proto\x12\x0fphantom_flow.ml\"\xb4\x01\n" +
	"\x0ePredictRequest\x12\x1a\n" +
	"\bfeatures\x18\x01 \x03(\x01R\bfeatures\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x02 \x01(\tR\tipAddress\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x03 \x01(\tR\tuserAgent\x12!\n" +
	"\frequest_path\x18\x04 \x01(\tR\vrequestPath\x12%\n" +
	"\x0erequest_method\x18\x05 \x01(\tR\rrequestMethod\"\xa9\x01\n" +
	"\x0fPredictResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12!\n" +
	"\fthreat_score\x18\x02 \x01(\x01R\vthreatScore\x12#\n" +
	"\ranomaly_score\x18\x03 \x01(\x01R\fanomalyScore\x12\x1e\n" +
	"\n" +
	"confidence\x18\x04 \x01(\x01R\n" +
	"confidence\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error2[\n" +
	"\vMLInference\x12L\n" +
	"\aPredict\x12\x1f.phantom_flow.ml.PredictRequest\x1a .phantom_flow.ml.PredictResponseB4Z2github.com/phantom-flow/security-platform/proto/mlb\x06proto3"

var (
	file_ml_service_proto_rawDescOnce sync.Once
	file_ml_service_proto_rawDescData []byte
)

func file_ml_service_proto_rawDescGZIP() []byte {
	file_ml_service_proto_rawDescOnce.Do(func() {
		file_ml_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ml_service_proto_rawDesc), len(file_ml_service_proto_rawDesc)))
	})
	return file_ml_service_proto_rawDescData
}

var file_ml_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ml_service_proto_goTypes = []any{
	(*PredictRequest)(nil),  // 0: phantom_flow.ml.PredictRequest
	(*PredictResponse)(nil), // 1: phantom_flow.ml.PredictResponse
}
var file_ml_service_proto_depIdxs = []int32{
	0, // 0: phantom_flow.ml.MLInference.Predict:input_type -> phantom_flow.ml.PredictRequest
	1, // 1: phantom_flow.ml.MLInference.Predict:output_type -> phantom_flow.ml.PredictResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ml_service_proto_init() }
func file_ml_service_proto_init() {
	if File_ml_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ml_service_proto_rawDesc), len(file_ml_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ml_service_proto_goTypes,
		DependencyIndexes: file_ml_service_proto_depIdxs,
		MessageInfos:      file_ml_service_proto_msgTypes,
	}.Build()
	File_ml_service_proto = out.File
	file_ml_service_proto_goTypes = nil
	file_ml_service_proto_depIdxs = nil
}
