// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package ml

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

const MLInference_Predict_FullMethodName = "/phantom_flow.ml.MLInference/Predict"

type MLInferenceClient interface {
	Predict(ctx context.Context, in *PredictRequest, opts ...grpc.CallOption) (*PredictResponse, error)
}

type mlInferenceClient struct {
	cc grpc.ClientConnInterface
}

func NewMLInferenceClient(cc grpc.ClientConnInterface) MLInferenceClient {
	return &mlInferenceClient{cc}
}

func (c *mlInferenceClient) Predict(ctx context.Context, in *PredictRequest, opts ...grpc.CallOption) (*PredictResponse, error) {
	out := new(PredictResponse)
	err := c.cc.Invoke(ctx, MLInference_Predict_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

type MLInferenceServer interface {
	Predict(context.Context, *PredictRequest) (*PredictResponse, error)
	mustEmbedUnimplementedMLInferenceServer()
}

type UnimplementedMLInferenceServer struct{}

func (UnimplementedMLInferenceServer) Predict(context.Context, *PredictRequest) (*PredictResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Predict not implemented")
}

func (UnimplementedMLInferenceServer) mustEmbedUnimplementedMLInferenceServer() {}

type UnsafeMLInferenceServer interface {
	mustEmbedUnimplementedMLInferenceServer()
}

func RegisterMLInferenceServer(s grpc.ServiceRegistrar, srv MLInferenceServer) {
	s.RegisterService(&MLInference_ServiceDesc, srv)
}

func _MLInference_Predict_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PredictRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLInferenceServer).Predict(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLInference_Predict_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLInferenceServer).Predict(ctx, req.(*PredictRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var MLInference_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "phantom_flow.ml.MLInference",
	HandlerType: (*MLInferenceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Predict",
			Handler:    _MLInference_Predict_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ml_service.proto",
}
