// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: events.proto

package events

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ThreatDetectedEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EventId         string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	RequestId       string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ClientIp        string                 `protobuf:"bytes,3,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	ThreatScore     float64                `protobuf:"fixed64,4,opt,name=threat_score,json=threatScore,proto3" json:"threat_score,omitempty"`
	RiskLevel       string                 `protobuf:"bytes,5,opt,name=risk_level,json=riskLevel,proto3" json:"risk_level,omitempty"`
	ThreatType      string                 `protobuf:"bytes,6,opt,name=threat_type,json=threatType,proto3" json:"threat_type,omitempty"`
	RequestPath     string                 `protobuf:"bytes,7,opt,name=request_path,json=requestPath,proto3" json:"request_path,omitempty"`
	RequestMethod   string                 `protobuf:"bytes,8,opt,name=request_method,json=requestMethod,proto3" json:"request_method,omitempty"`
	SourceService   string                 `protobuf:"bytes,9,opt,name=source_service,json=sourceService,proto3" json:"source_service,omitempty"`
	TimestampUnixMs int64                  `protobuf:"varint,10,opt,name=timestamp_unix_ms,json=timestampUnixMs,proto3" json:"timestamp_unix_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ThreatDetectedEvent) Reset() {
	*x = ThreatDetectedEvent{}
	mi := &file_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThreatDetectedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThreatDetectedEvent) ProtoMessage() {}

func (x *ThreatDetectedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThreatDetectedEvent.ProtoReflect.Descriptor instead.
func (*ThreatDetectedEvent) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{0}
}

func (x *ThreatDetectedEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *ThreatDetectedEvent) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ThreatDetectedEvent) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *ThreatDetectedEvent) GetThreatScore() float64 {
	if x != nil {
		return x.ThreatScore
	}
	return 0
}

func (x *ThreatDetectedEvent) GetRiskLevel() string {
	if x != nil {
		return x.RiskLevel
	}
	return ""
}

func (x *ThreatDetectedEvent) GetThreatType() string {
	if x != nil {
		return x.ThreatType
	}
	return ""
}

func (x *ThreatDetectedEvent) GetRequestPath() string {
	if x != nil {
		return x.RequestPath
	}
	return ""
}

func (x *ThreatDetectedEvent) GetRequestMethod() string {
	if x != nil {
		return x.RequestMethod
	}
	return ""
}

func (x *ThreatDetectedEvent) GetSourceService() string {
	if x != nil {
		return x.SourceService
	}
	return ""
}

func (x *ThreatDetectedEvent) GetTimestampUnixMs() int64 {
	if x != nil {
		return x.TimestampUnixMs
	}
	return 0
}

type ResponseExecutedEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EventId         string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	RequestId       string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ClientIp        string                 `protobuf:"bytes,3,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	ActionType      string                 `protobuf:"bytes,4,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"`
	Target          string                 `protobuf:"bytes,5,opt,name=target,proto3" json:"target,omitempty"`
	Success         bool                   `protobuf:"varint,6,opt,name=success,proto3" json:"success,omitempty"`
	DurationMs      float64                `protobuf:"fixed64,7,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	ThreatId        string                 `protobuf:"bytes,8,opt,name=threat_id,json=threatId,proto3" json:"threat_id,omitempty"`
	SourceService   string                 `protobuf:"bytes,9,opt,name=source_service,json=sourceService,proto3" json:"source_service,omitempty"`
	TimestampUnixMs int64                  `protobuf:"varint,10,opt,name=timestamp_unix_ms,json=timestampUnixMs,proto3" json:"timestamp_unix_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ResponseExecutedEvent) Reset() {
	*x = ResponseExecutedEvent{}
	mi := &file_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseExecutedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseExecutedEvent) ProtoMessage() {}

func (x *ResponseExecutedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseExecutedEvent.ProtoReflect.Descriptor instead.
func (*ResponseExecutedEvent) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{1}
}

func (x *ResponseExecutedEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *ResponseExecutedEvent) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ResponseExecutedEvent) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *ResponseExecutedEvent) GetActionType() string {
	if x != nil {
		return x.ActionType
	}
	return ""
}

func (x *ResponseExecutedEvent) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *ResponseExecutedEvent) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ResponseExecutedEvent) GetDurationMs() float64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *ResponseExecutedEvent) GetThreatId() string {
	if x != nil {
		return x.ThreatId
	}
	return ""
}

func (x *ResponseExecutedEvent) GetSourceService() string {
	if x != nil {
		return x.SourceService
	}
	return ""
}

func (x *ResponseExecutedEvent) GetTimestampUnixMs() int64 {
	if x != nil {
		return x.TimestampUnixMs
	}
	return 0
}

var File_events_proto protoreflect.FileDescriptor

const file_events_proto_rawDesc = "" +
	"\n" +
	"\fevents.proto\x12\x13phantom_flow.events\"\xec\x02\n" +
	"\x13ThreatDetectedEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12\x1b\n" +
	"\tclient_ip\x18\x03 \x01(\tR\bclientIp\x12!\n" +
	"\fthreat_score\x18\x04 \x01(\x01R\vthreatScore\x12\x1d\n" +
	"\n" +
	"risk_level\x18\x05 \x01(\tR\triskLevel\x12\x1f\n" +
	"\vthreat_type\x18\x06 \x01(\tR\n" +
	"threatType\x12!\n" +
	"\frequest_path\x18\a \x01(\tR\vrequestPath\x12%\n" +
	"\x0erequest_method\x18\b \x01(\tR\rrequestMethod\x12%\n" +
	"\x0esource_service\x18\t \x01(\tR\rsourceService\x12*\n" +
	"\x11timestamp_unix_ms\x18\n" +
	" \x01(\x03R\x0ftimestampUnixMs\"\xd2\x02\n" +
	"\x15ResponseExecutedEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12\x1b\n" +
	"\tclient_ip\x18\x03 \x01(\tR\bclientIp\x12\x1f\n" +
	"\vaction_type\x18\x04 \x01(\tR\n" +
	"actionType\x12\x16\n" +
	"\x06target\x18\x05 \x01(\tR\x06target\x12\x18\n" +
	"\asuccess\x18\x06 \x01(\bR\asuccess\x12\x1f\n" +
	"\vduration_ms\x18\a \x01(\x01R\n" +
	"durationMs\x12\x1b\n" +
	"\tthreat_id\x18\b \x01(\tR\bthreatId\x12%\n" +
	"\x0esource_service\x18\t \x01(\tR\rsourceService\x12*\n" +
	"\x11timestamp_unix_ms\x18\n" +
	" \x01(\x03R\x0ftimestampUnixMsB8Z6github.com/phantom-flow/security-platform/proto/eventsb\x06proto3"

var (
	file_events_proto_rawDescOnce sync.Once
	file_events_proto_rawDescData []byte
)

func file_events_proto_rawDescGZIP() []byte {
	file_events_proto_rawDescOnce.Do(func() {
		file_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_events_proto_rawDesc), len(file_events_proto_rawDesc)))
	})
	return file_events_proto_rawDescData
}

var file_events_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_events_proto_goTypes = []any{
	(*ThreatDetectedEvent)(nil),   // 0: phantom_flow.events.ThreatDetectedEvent
	(*ResponseExecutedEvent)(nil), // 1: phantom_flow.events.ResponseExecutedEvent
}
var file_events_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_events_proto_init() }
func file_events_proto_init() {
	if File_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_events_proto_rawDesc), len(file_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_events_proto_goTypes,
		DependencyIndexes: file_events_proto_depIdxs,
		MessageInfos:      file_events_proto_msgTypes,
	}.Build()
	File_events_proto = out.File
	file_events_proto_goTypes = nil
	file_events_proto_depIdxs = nil
}
