// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: threat_service.proto

package threat

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ThreatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ClientIp      string                 `protobuf:"bytes,2,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	UserAgent     string                 `protobuf:"bytes,3,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	RequestMethod string                 `protobuf:"bytes,4,opt,name=request_method,json=requestMethod,proto3" json:"request_method,omitempty"`
	RequestPath   string                 `protobuf:"bytes,5,opt,name=request_path,json=requestPath,proto3" json:"request_path,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,6,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          []byte                 `protobuf:"bytes,7,opt,name=body,proto3" json:"body,omitempty"`
	SessionId     string                 `protobuf:"bytes,8,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserId        string                 `protobuf:"bytes,9,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThreatRequest) Reset() {
	*x = ThreatRequest{}
	mi := &file_threat_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThreatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThreatRequest) ProtoMessage() {}

func (x *ThreatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_threat_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThreatRequest.ProtoReflect.Descriptor instead.
func (*ThreatRequest) Descriptor() ([]byte, []int) {
	return file_threat_service_proto_rawDescGZIP(), []int{0}
}

func (x *ThreatRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ThreatRequest) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *ThreatRequest) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *ThreatRequest) GetRequestMethod() string {
	if x != nil {
		return x.RequestMethod
	}
	return ""
}

func (x *ThreatRequest) GetRequestPath() string {
	if x != nil {
		return x.RequestPath
	}
	return ""
}

func (x *ThreatRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *ThreatRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ThreatRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ThreatRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ThreatResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Success           bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ThreatScore       float64                `protobuf:"fixed64,2,opt,name=threat_score,json=threatScore,proto3" json:"threat_score,omitempty"`
	Confidence        float64                `protobuf:"fixed64,3,opt,name=confidence,proto3" json:"confidence,omitempty"`
	RiskLevel         string                 `protobuf:"bytes,4,opt,name=risk_level,json=riskLevel,proto3" json:"risk_level,omitempty"`
	ThreatType        string                 `protobuf:"bytes,5,opt,name=threat_type,json=threatType,proto3" json:"threat_type,omitempty"`
	SignaturesMatched []string               `protobuf:"bytes,6,rep,name=signatures_matched,json=signaturesMatched,proto3" json:"signatures_matched,omitempty"`
	Error             string                 `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ThreatResponse) Reset() {
	*x = ThreatResponse{}
	mi := &file_threat_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThreatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThreatResponse) ProtoMessage() {}

func (x *ThreatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_threat_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThreatResponse.ProtoReflect.Descriptor instead.
func (*ThreatResponse) Descriptor() ([]byte, []int) {
	return file_threat_service_proto_rawDescGZIP(), []int{1}
}

func (x *ThreatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ThreatResponse) GetThreatScore() float64 {
	if x != nil {
		return x.ThreatScore
	}
	return 0
}

func (x *ThreatResponse) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *ThreatResponse) GetRiskLevel() string {
	if x != nil {
		return x.RiskLevel
	}
	return ""
}

func (x *ThreatResponse) GetThreatType() string {
	if x != nil {
		return x.ThreatType
	}
	return ""
}

func (x *ThreatResponse) GetSignaturesMatched() []string {
	if x != nil {
		return x.SignaturesMatched
	}
	return nil
}

func (x *ThreatResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_threat_service_proto protoreflect.FileDescriptor

const file_threat_service_proto_rawDesc = "" +
	"\n" +
	"\x14threat_service.proto\x12\x13phantom_flow.threat\"\x87\x03\n" +
	"\rThreatRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1b\n" +
	"\tclient_ip\x18\x02 \x01(\tR\bclientIp\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x03 \x01(\tR\tuserAgent\x12%\n" +
	"\x0erequest_method\x18\x04 \x01(\tR\rrequestMethod\x12!\n" +
	"\frequest_path\x18\x05 \x01(\tR\vrequestPath\x12I\n" +
	"\aheaders\x18\x06 \x03(\v2/.phantom_flow.threat.ThreatRequest.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\a \x01(\fR\x04body\x12\x1d\n" +
	"\n" +
	"session_id\x18\b \x01(\tR\tsessionId\x12\x17\n" +
	"\auser_id\x18\t \x01(\tR\x06userId\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf2\x01\n" +
	"\x0eThreatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12!\n" +
	"\fthreat_score\x18\x02 \x01(\x01R\vthreatScore\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x01R\n" +
	"confidence\x12\x1d\n" +
	"\n" +
	"risk_level\x18\x04 \x01(\tR\triskLevel\x12\x1f\n" +
	"\vthreat_type\x18\x05 \x01(\tR\n" +
	"threatType\x12-\n" +
	"\x12signatures_matched\x18\x06 \x03(\tR\x11signaturesMatched\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error2j\n" +
	"\x0eThreatAnalysis\x12X\n" +
	"\rAnalyzeThreat\x12\".phantom_flow.threat.ThreatRequest\x1a#.phantom_flow.threat.ThreatResponseB8Z6github.com/phantom-flow/security-platform/proto/threatb\x06proto3"

var (
	file_threat_service_proto_rawDescOnce sync.Once
	file_threat_service_proto_rawDescData []byte
)

func file_threat_service_proto_rawDescGZIP() []byte {
	file_threat_service_proto_rawDescOnce.Do(func() {
		file_threat_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_threat_service_proto_rawDesc), len(file_threat_service_proto_rawDesc)))
	})
	return file_threat_service_proto_rawDescData
}

var file_threat_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_threat_service_proto_goTypes = []any{
	(*ThreatRequest)(nil),  // 0: phantom_flow.threat.ThreatRequest
	(*ThreatResponse)(nil), // 1: phantom_flow.threat.ThreatResponse
	nil,                    // 2: phantom_flow.threat.ThreatRequest.HeadersEntry
}
var file_threat_service_proto_depIdxs = []int32{
	2, // 0: phantom_flow.threat.ThreatRequest.headers:type_name -> phantom_flow.threat.ThreatRequest.HeadersEntry
	0, // 1: phantom_flow.threat.ThreatAnalysis.AnalyzeThreat:input_type -> phantom_flow.threat.ThreatRequest
	1, // 2: phantom_flow.threat.ThreatAnalysis.AnalyzeThreat:output_type -> phantom_flow.threat.ThreatResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_threat_service_proto_init() }
func file_threat_service_proto_init() {
	if File_threat_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_threat_service_proto_rawDesc), len(file_threat_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_threat_service_proto_goTypes,
		DependencyIndexes: file_threat_service_proto_depIdxs,
		MessageInfos:      file_threat_service_proto_msgTypes,
	}.Build()
	File_threat_service_proto = out.File
	file_threat_service_proto_goTypes = nil
	file_threat_service_proto_depIdxs = nil
}
