// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package threat

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

const ThreatAnalysis_AnalyzeThreat_FullMethodName = "/phantom_flow.threat.ThreatAnalysis/AnalyzeThreat"

type ThreatAnalysisClient interface {
	AnalyzeThreat(ctx context.Context, in *ThreatRequest, opts ...grpc.CallOption) (*ThreatResponse, error)
}

type threatAnalysisClient struct {
	cc grpc.ClientConnInterface
}

func NewThreatAnalysisClient(cc grpc.ClientConnInterface) ThreatAnalysisClient {
	return &threatAnalysisClient{cc}
}

func (c *threatAnalysisClient) AnalyzeThreat(ctx context.Context, in *ThreatRequest, opts ...grpc.CallOption) (*ThreatResponse, error) {
	out := new(ThreatResponse)
	err := c.cc.Invoke(ctx, ThreatAnalysis_AnalyzeThreat_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

type ThreatAnalysisServer interface {
	AnalyzeThreat(context.Context, *ThreatRequest) (*ThreatResponse, error)
	mustEmbedUnimplementedThreatAnalysisServer()
}

type UnimplementedThreatAnalysisServer struct{}

func (UnimplementedThreatAnalysisServer) AnalyzeThreat(context.Context, *ThreatRequest) (*ThreatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AnalyzeThreat not implemented")
}

func (UnimplementedThreatAnalysisServer) mustEmbedUnimplementedThreatAnalysisServer() {}

type UnsafeThreatAnalysisServer interface {
	mustEmbedUnimplementedThreatAnalysisServer()
}

func RegisterThreatAnalysisServer(s grpc.ServiceRegistrar, srv ThreatAnalysisServer) {
	s.RegisterService(&ThreatAnalysis_ServiceDesc, srv)
}

func _ThreatAnalysis_AnalyzeThreat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ThreatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThreatAnalysisServer).AnalyzeThreat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ThreatAnalysis_AnalyzeThreat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThreatAnalysisServer).AnalyzeThreat(ctx, req.(*ThreatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var ThreatAnalysis_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "phantom_flow.threat.ThreatAnalysis",
	HandlerType: (*ThreatAnalysisServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AnalyzeThreat",
			Handler:    _ThreatAnalysis_AnalyzeThreat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "threat_service.proto",
}
